# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - reco-akeneo-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Check if composer.json exists
        id: check_files_composer
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.lock'

      - name: Run composer install if composer.json exists
        if: steps.check_files_composer.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Check if yarn.lock exists
        id: check_files_yarn
        uses: andstor/file-existence-action@v1
        with:
          files: 'yarn.lock'

      - name: Run yarn install if composer.json exists
        if: steps.check_files_yarn.outputs.files_exists == 'true'
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 yarn install && rm -rf public/bundles public/js && php bin/console pim:installer:assets --symlink --clean && PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 yarn packages:build && rm -rf public/dist && yarn run webpack && rm -rf public/css && yarn run less && yarn run update-extensions

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'reco-akeneo-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
